language: scala
scala:
- 2.10.4
script: sbt clean test
jdk:
- openjdk8
notifications:
  email:
    recipients:
    - peter.rigole@atomicbits.io
env:
  global:
  - secure: KKvDXePSzM4zpjCML7nR22FWqV75LvuVlQZBbEjrtlgty5MkhfeqlVLHRNrWz1GcoKTBzp9B1WWtYRT8lxIie/xxsoZSSYXoMGx+AU+5DFxrkix0U7ipqej7i++Umxmz0nGQEwbMA5cKc+t7oonXHTcJsyAhPVHAI6vN3ghru4baazHl83j/BWUtcz46lWFqq32lI6A3kt3o6d9zFDkU4tHZSgtOnGiTgSEaX3pJ5h0+CKJzpmxTU7gmwRmoNZDo8rBUI+aUQM4UNkZp2NkjJYXdLYtn2ylOZLU0L5ho9wTk9sgbTk8PtOE1MJIS2CS6iADiFnhvL6xpjIwB5cz2meHhvdEBD95bTlvE8k05+vnSqHzmnjb2/gMHV6FAtWjh3ZKtCMiK6KTWBWxXQxKaWjDNNdBcEpp+tuwG/Y/o4lGtFUMyYyn+OTJEjJM603eD66P1ISXt+VpRRWUlBW6UHDYPKnQtoJ75AdvY3QJnM7RHwYTTf2T4ULeG9D3TBm0UMeW2Huex4NS9esN95xBGan5B4cQ9ljRdKLtw7KxJC4a3xqiq5KkiPng0xaCn1xX+A7G3V5VsCohFaRD4ya0jZsvbvSERqQghGWBZZ0T/Q353kYfw3FhGv6OSTd1Ck09XRtFz5cniejwqdpiaqdSxeN7WmgVcepnZNS6F0kmLC2c=
  - secure: NHl497PXDTZVuZHluPFmJc3bM8VbNmLqfeMVi9l+fr3WG7+CBPNckRuCaJxLpyAgVBcAA8QwAsYEyuwhXCdXPBORJB+h3Bo3EJD+kzGHV9JLIqcdD4neS/5SEJ+dMl/O9I6LozpenTElVseGVflrzquIkdes45GFIy/vcEewWBp7HKHx/v2ittPCXPl69yrhuSUJqr1laJzBBBkgCUf3tATGYJUGyHxr6YU5P6zeDJ0XFWuLMX9hhRkSYpBkbf0mfdrScSnfkfREQ5z+XBSEVPDZ565/9D68KycacX/E77cDYfLnhzlpDcEysy+9v9i9R9vKoTkU0N3YNtvFHSgd1l1NBMm/xrX4su/K9ZOPJTUpnFHL6qUyClYkJ/KIRkYxOYb9TqGTNTO1z3WSQuvPYqKhJTTk0A8XPqHRMVKwxL/iNV0nO7Gknbkb6WweITvgFH/G16H9p80G2eCGP2IqA0UO9TBngRaoAorG7QXBjT383w+JdEUsgnAf5Kp+WJUdfkR0m3LRdidaLv6t3Dt8uJkzm84reG4sL9KIABK04xe5d/o9n+XuSIwFgEd9s4p8OzOsar306PD68HeKkAEF0wN3zXH+UB9/ao0popp7ZgbFv+l9XqnjqAiqOuTjla5V2abNYce5MzjjHCyJ52AOwDCP4PgrmeGvzIY4DwbQ7wg=
