language: scala
scala:
- 2.10.4
script: sbt clean test
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
    - peter.rigole@atomicbits.io
after_success:
- '[[ $TRAVIS_BRANCH == "develop" ]] && { sbt publish; };'

env:
  global:
  - secure: "EYnx3m8Cs/3qDAzVx3AvLtxyucrnEjNaHlrVN6BwABQFT2ZdmYjLL0954r+VjqdqYSjXK6G7cCg2AgNOlhXkd2Ac0dR8jOTfIiaVB1brRtX2kuvhVh0Tt1kBEDwXLHersDhnP5tMSZgqV3FvXb8VqpQvGoBLcYBl823gmT6/hpc+xkqJCBCDfKyQgFmhYT21vMPf8CeI6ZNnErywpASbIpZ5vYwREU51V9E7j2XbvNPy9ObLzwxXxzNfxdGdtnN/qJPBhxs7E6Ibxyp1KQwa1PSpHRJayjo4Jw2IfBwpRhUzj4FRU1NgKZTFWaL09J6wICBlkRLt9S2JMoHSFSTL83K2aOr1W5AfEkBN4YNVHzaQA2U/Wv4XYJjrAHk8HAb3/01aSOhRsU6grekahsxx+T2cDpEIX/EeJZCpQ1JpNICgmtbyXa99dTC6W1rNknF2t3g8VETMveb0C9WhKR1KebU0ZL4z+RfRi2g3Nt4GADfcqdzMbWIeGOvSrn7yaFsAGURziSHCU03TOhf9RfWNdzLSXwRyoFW4JW2zghOPvNCReaB7q9OnglAGjBVMxLaZcANx3tfKaInY/paDPDRXcV38UQN9/oUIHvokp5NniDo9NhHidisPuinNkxAHTTPih+a2rjuO6bojl2NasYGUkhgJoGrisK7eVr13qq/FkCc="

