language: scala
scala:
- 2.10.4
script: sbt clean test
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
    - peter.rigole@atomicbits.io
after_success:
- '[[ $TRAVIS_BRANCH == "develop" ]] && { sbt publish; };'

env:
  global:
  - secure: gfeKN+bGlG6LkD1yBxdY37D+12elwoBjVov1n4Slyp1L4OTWz+c9XG6kbqh9H/kiipbniFN1w/+O0cMlczKp9UzBchSHeq2U88IWDPCWFMysAIZVIahllfVj68om16wZU2SQLiM0SV91Qlzu7isvAn8kvY/Btu6Xm3qZNmxj9TWgVKdURXyf6U/boEl43WYk5RzdmaPoUCMn14cil0fuBkzwlqYuh7Ipq7EeDVskdcA7gJDfkC1c6VZW6L4DVqofFn1qE1PgyEfi1UV8qMyx6maMRhb8JzQoWWkOT141+GoV/iUnZ3wtrjWGno76u9teS2MPxPtUOE6yb7hut3nHg72oPyXmiSborflQn8/YRuj3setcJpByvnSAcWAB2HVQnLzbXX99DKFUDEtNI1go1JiPfut/p4lj9KUe7MMR3Z8LyvyY0DGw5C9wnNjL1PMW7zBX81f1qhbsEtujmvYcBvz2AoMuL02+f3TTXpulJK92Cqjt2d7v5kQI09Dtzz1ceNvUhNPR/LloFjF3KOZNMEtntbM79khEDtHk9nm1BZAfyAkIqhcH+SrEvz4PzW8yD4pf1HhLb6q4TSipSWPBHILhRclwmyHwJJofd10UIhLUv9yinq0WeDdbvzXx2+nmBWHucV+EugGO0oi/ddwsMeTaaP/U7vAdHN9n9GgoDzE=
  - secure: "EYnx3m8Cs/3qDAzVx3AvLtxyucrnEjNaHlrVN6BwABQFT2ZdmYjLL0954r+VjqdqYSjXK6G7cCg2AgNOlhXkd2Ac0dR8jOTfIiaVB1brRtX2kuvhVh0Tt1kBEDwXLHersDhnP5tMSZgqV3FvXb8VqpQvGoBLcYBl823gmT6/hpc+xkqJCBCDfKyQgFmhYT21vMPf8CeI6ZNnErywpASbIpZ5vYwREU51V9E7j2XbvNPy9ObLzwxXxzNfxdGdtnN/qJPBhxs7E6Ibxyp1KQwa1PSpHRJayjo4Jw2IfBwpRhUzj4FRU1NgKZTFWaL09J6wICBlkRLt9S2JMoHSFSTL83K2aOr1W5AfEkBN4YNVHzaQA2U/Wv4XYJjrAHk8HAb3/01aSOhRsU6grekahsxx+T2cDpEIX/EeJZCpQ1JpNICgmtbyXa99dTC6W1rNknF2t3g8VETMveb0C9WhKR1KebU0ZL4z+RfRi2g3Nt4GADfcqdzMbWIeGOvSrn7yaFsAGURziSHCU03TOhf9RfWNdzLSXwRyoFW4JW2zghOPvNCReaB7q9OnglAGjBVMxLaZcANx3tfKaInY/paDPDRXcV38UQN9/oUIHvokp5NniDo9NhHidisPuinNkxAHTTPih+a2rjuO6bojl2NasYGUkhgJoGrisK7eVr13qq/FkCc="

